BEGIN;
INSERT INTO products (store_id, slug, name_ar, description_ar, price, image_path, unit, tags, sort_order)
VALUES
((SELECT id FROM stores WHERE slug='safra-jewellery'), 'safra-jewellery-1', 'طقم زواج ذهب عيار 21', 'طقم كامل: عقد وأسورة وخاتم وحلق، بشغل خليجي.', 8450, '/demo/gold-1.jpg', 'للطقم', ARRAY['أطقم زواج','عيار 21']::text[], 10),
((SELECT id FROM stores WHERE slug='safra-jewellery'), 'safra-jewellery-2', 'خاتم خطوبة سوليتير', 'خاتم بفص ألماس مركزي وشهادة أصالة.', 3200, '/demo/gold-2.jpg', 'للقطعة', ARRAY['خواتم','ألماس']::text[], 20),
((SELECT id FROM stores WHERE slug='safra-jewellery'), 'safra-jewellery-3', 'أسورة ذهب مجدولة', 'أسورة عيار 21 بوزن 12 جراماً تقريباً.', 2750, '/demo/gold-3.jpg', 'للقطعة', ARRAY['أساور','عيار 21']::text[], 30),
((SELECT id FROM stores WHERE slug='safra-jewellery'), 'safra-jewellery-4', 'عقد ذهب ناعم', 'عقد يومي خفيف مناسب للهدايا.', 1890, '/demo/gold-4.jpg', 'للقطعة', ARRAY['عقود','هدايا']::text[], 40),
((SELECT id FROM stores WHERE slug='qassim-gold'), 'qassim-gold-1', 'سبيكة ذهب 10 جرام', 'سبيكة معتمدة بختم المصنع وشهادة وزن.', 3950, '/demo/gold-5.jpg', 'للسبيكة', ARRAY['سبائك','عيار 24']::text[], 10),
((SELECT id FROM stores WHERE slug='qassim-gold'), 'qassim-gold-2', 'جنيه ذهب سعودي', 'جنيه ذهب بوزن 8 جرامات، سعر اليوم.', 1420, '/demo/gold-6.jpg', 'للجنيه', ARRAY['جنيهات','عيار 21']::text[], 20),
((SELECT id FROM stores WHERE slug='qassim-gold'), 'qassim-gold-3', 'ذهب عيار 21 — بالجرام', 'السعر يتغيّر يومياً مع سعر السوق.', 268, '/demo/gold-7.jpg', 'للجرام', ARRAY['عيار 21','بيع بالجرام']::text[], 30),
((SELECT id FROM stores WHERE slug='qassim-gold'), 'qassim-gold-4', 'سبيكة ذهب 50 جرام', 'للاستثمار، مع علبة حفظ.', 19500, '/demo/gold-8.jpg', 'للسبيكة', ARRAY['سبائك','استثمار']::text[], 40),
((SELECT id FROM stores WHERE slug='durrat-albahr'), 'durrat-albahr-1', 'طقم لؤلؤ طبيعي', 'لؤلؤ طبيعي مع إطار ذهب أبيض.', 4300, '/demo/gold-9.jpg', 'للطقم', ARRAY['لؤلؤ','أطقم']::text[], 10),
((SELECT id FROM stores WHERE slug='durrat-albahr'), 'durrat-albahr-2', 'خاتم ألماس كلاسيكي', 'قطعة بشهادة GIA.', 6800, '/demo/gold-10.jpg', 'للقطعة', ARRAY['ألماس','خواتم']::text[], 20),
((SELECT id FROM stores WHERE slug='durrat-albahr'), 'durrat-albahr-3', 'حلق ذهب أبيض', 'تصميم هادئ للاستخدام اليومي.', 2150, '/demo/gold-11.jpg', 'للقطعة', ARRAY['حلق','ذهب أبيض']::text[], 30),
((SELECT id FROM stores WHERE slug='durrat-albahr'), 'durrat-albahr-4', 'دبلة زواج مزدوجة', 'دبلتان بنقش داخلي مجاني.', 3400, '/demo/gold-12.jpg', 'للطقم', ARRAY['دبل','أطقم زواج']::text[], 40),
((SELECT id FROM stores WHERE slug='bin-saleh-gold'), 'bin-saleh-gold-1', 'خاتم ذهب رجالي', 'خاتم عريض بفص عقيق.', 1650, '/demo/gold-2.jpg', 'للقطعة', ARRAY['رجالي','عيار 21']::text[], 10),
((SELECT id FROM stores WHERE slug='bin-saleh-gold'), 'bin-saleh-gold-2', 'سلسال ذهب طويل', 'طول 60 سم بقفل أمان.', 2380, '/demo/gold-4.jpg', 'للقطعة', ARRAY['سلاسل','عيار 21']::text[], 20),
((SELECT id FROM stores WHERE slug='bin-saleh-gold'), 'bin-saleh-gold-3', 'طقم أطفال ذهب', 'طقم مواليد: أسورة وحلق صغير.', 980, '/demo/gold-3.jpg', 'للطقم', ARRAY['أطفال','هدايا']::text[], 30),
((SELECT id FROM stores WHERE slug='waqt-watches'), 'waqt-watches-1', 'ساعة سويسرية أوتوماتيك', 'حركة أوتوماتيك بضمان وكيل 5 سنوات.', 14500, '/demo/watch-1.jpg', 'للقطعة', ARRAY['سويسري','أوتوماتيك']::text[], 10),
((SELECT id FROM stores WHERE slug='waqt-watches'), 'waqt-watches-2', 'ساعة كرونوغراف فولاذ', 'مقاومة للماء 100 متر.', 6900, '/demo/watch-2.jpg', 'للقطعة', ARRAY['كرونوغراف','فولاذ']::text[], 20),
((SELECT id FROM stores WHERE slug='waqt-watches'), 'waqt-watches-3', 'ساعة كلاسيك بحزام جلد', 'مينا أبيض وحزام جلد إيطالي.', 3450, '/demo/watch-3.jpg', 'للقطعة', ARRAY['كلاسيك','جلد']::text[], 30),
((SELECT id FROM stores WHERE slug='waqt-watches'), 'waqt-watches-4', 'ساعة نسائية صغيرة', 'قطر 28 مم بإطار مرصّع.', 2780, '/demo/watch-4.jpg', 'للقطعة', ARRAY['نسائي','هدايا']::text[], 40),
((SELECT id FROM stores WHERE slug='elegance-bags'), 'elegance-bags-1', 'حقيبة يد جلد طبيعي', 'جلد بقري طبيعي مع حزام كتف.', 1450, '/demo/bag-1.jpg', 'للقطعة', ARRAY['حقائب نسائية','جلد']::text[], 10),
((SELECT id FROM stores WHERE slug='elegance-bags'), 'elegance-bags-2', 'حقيبة كتف صغيرة', 'مناسبة للمناسبات والخروج القصير.', 690, '/demo/bag-2.jpg', 'للقطعة', ARRAY['حقائب نسائية']::text[], 20),
((SELECT id FROM stores WHERE slug='elegance-bags'), 'elegance-bags-3', 'حقيبة سفر كبيرة', 'سعة 45 لتراً بعجلات صامتة.', 1980, '/demo/bag-3.jpg', 'للقطعة', ARRAY['حقائب سفر']::text[], 30),
((SELECT id FROM stores WHERE slug='elegance-bags'), 'elegance-bags-4', 'محفظة نسائية', 'بها 12 جيباً للبطاقات.', 340, '/demo/bag-4.jpg', 'للقطعة', ARRAY['محافظ','هدايا']::text[], 40),
((SELECT id FROM stores WHERE slug='time-house'), 'time-house-1', 'تغيير بطارية ساعة', 'بطارية أصلية مع اختبار مقاومة الماء.', 45, '/demo/watch-5.jpg', 'للخدمة', ARRAY['بطاريات','خدمة']::text[], 10),
((SELECT id FROM stores WHERE slug='time-house'), 'time-house-2', 'حزام جلد بديل', 'مقاسات 18–22 مم.', 180, '/demo/watch-6.jpg', 'للقطعة', ARRAY['أحزمة','جلد']::text[], 20),
((SELECT id FROM stores WHERE slug='time-house'), 'time-house-3', 'ساعة كلاسيكية بسيطة', 'خيار اقتصادي بجودة جيدة.', 890, '/demo/watch-7.jpg', 'للقطعة', ARRAY['كلاسيك']::text[], 30),
((SELECT id FROM stores WHERE slug='leather-corner'), 'leather-corner-1', 'حقيبة مكتب جلد', 'تتسع للابتوب 16 بوصة.', 1250, '/demo/bag-5.jpg', 'للقطعة', ARRAY['حقائب مكتب','جلد طبيعي']::text[], 10),
((SELECT id FROM stores WHERE slug='leather-corner'), 'leather-corner-2', 'محفظة رجالية بحفر اسم', 'الحفر مجاني ويستغرق يوماً.', 260, '/demo/bag-6.jpg', 'للقطعة', ARRAY['محافظ','حفر أسماء']::text[], 20),
((SELECT id FROM stores WHERE slug='leather-corner'), 'leather-corner-3', 'حزام جلد رجالي', 'جلد طبيعي بإبزيم فولاذ.', 190, '/demo/bag-7.jpg', 'للقطعة', ARRAY['أحزمة','جلد طبيعي']::text[], 30),
((SELECT id FROM stores WHERE slug='qasr-alaqmisha'), 'qasr-alaqmisha-1', 'قماش عباية كريب ياباني', 'عرض 150 سم، ثقيل ولا يشفّ.', 145, '/demo/fabric-1.jpg', 'للمتر', ARRAY['أقمشة عبايات','كريب']::text[], 10),
((SELECT id FROM stores WHERE slug='qasr-alaqmisha'), 'qasr-alaqmisha-2', 'قماش ثوب صيفي', 'قطن مخلوط مريح في الحر.', 95, '/demo/fabric-2.jpg', 'للمتر', ARRAY['قماش ثياب','صيفي']::text[], 20),
((SELECT id FROM stores WHERE slug='qasr-alaqmisha'), 'qasr-alaqmisha-3', 'قماش شتوي فاخر', 'صوف مخلوط بملمس ناعم.', 210, '/demo/fabric-3.jpg', 'للمتر', ARRAY['قماش ثياب','شتوي']::text[], 30),
((SELECT id FROM stores WHERE slug='qasr-alaqmisha'), 'qasr-alaqmisha-4', 'تفصيل ثوب رجالي', 'التسليم خلال ثلاثة أيام عمل.', 260, '/demo/fabric-4.jpg', 'للثوب', ARRAY['تفصيل']::text[], 40),
((SELECT id FROM stores WHERE slug='sahar-dresses'), 'sahar-dresses-1', 'فستان سهرة طويل', 'تطريز يدوي وذيل قصير.', 2450, '/demo/dress-1.jpg', 'للقطعة', ARRAY['فساتين سهرة']::text[], 10),
((SELECT id FROM stores WHERE slug='sahar-dresses'), 'sahar-dresses-2', 'فستان خطوبة', 'قابل للتعديل على المقاس مجاناً.', 3900, '/demo/dress-2.jpg', 'للقطعة', ARRAY['فساتين خطوبة']::text[], 20),
((SELECT id FROM stores WHERE slug='sahar-dresses'), 'sahar-dresses-3', 'فستان سهرة قصير', 'مناسب للحفلات العائلية.', 1350, '/demo/dress-3.jpg', 'للقطعة', ARRAY['فساتين سهرة']::text[], 30),
((SELECT id FROM stores WHERE slug='sahar-dresses'), 'sahar-dresses-4', 'تفصيل فستان بالمقاس', 'من قماشك أو من أقمشة المحل.', 1800, '/demo/dress-4.jpg', 'للفستان', ARRAY['تفصيل نسائي']::text[], 40),
((SELECT id FROM stores WHERE slug='abaya-almisk'), 'abaya-almisk-1', 'عباية يومية سادة', 'كريب خفيف بأكمام واسعة.', 320, '/demo/abaya-1.jpg', 'للقطعة', ARRAY['عباية يومية']::text[], 10),
((SELECT id FROM stores WHERE slug='abaya-almisk'), 'abaya-almisk-2', 'عباية مناسبات مطرّزة', 'تطريز يدوي على الأكمام.', 780, '/demo/abaya-2.jpg', 'للقطعة', ARRAY['عبايات مناسبات','تطريز']::text[], 20),
((SELECT id FROM stores WHERE slug='abaya-almisk'), 'abaya-almisk-3', 'عباية صلاة', 'قطعة واحدة سهلة اللبس.', 190, '/demo/abaya-3.jpg', 'للقطعة', ARRAY['عباية صلاة']::text[], 30),
((SELECT id FROM stores WHERE slug='abaya-almisk'), 'abaya-almisk-4', 'طرحة مطرّزة', 'تنسّق مع عبايات المناسبات.', 120, '/demo/abaya-4.jpg', 'للقطعة', ARRAY['طرح','تطريز']::text[], 40),
((SELECT id FROM stores WHERE slug='kids-world-qsm'), 'kids-world-qsm-1', 'طقم عيد أولاد', 'قميص وبنطال من 2 إلى 10 سنوات.', 245, '/demo/kids-1.jpg', 'للطقم', ARRAY['أطقم عيد','أولاد']::text[], 10),
((SELECT id FROM stores WHERE slug='kids-world-qsm'), 'kids-world-qsm-2', 'فستان بنات مناسبات', 'قطن مبطّن مريح.', 310, '/demo/kids-2.jpg', 'للقطعة', ARRAY['بنات','مناسبات']::text[], 20),
((SELECT id FROM stores WHERE slug='kids-world-qsm'), 'kids-world-qsm-3', 'زي مدرسي', 'قماش لا يحتاج كوي.', 165, '/demo/kids-3.jpg', 'للطقم', ARRAY['ملابس مدارس']::text[], 30),
((SELECT id FROM stores WHERE slug='kids-world-qsm'), 'kids-world-qsm-4', 'طقم مواليد قطن', 'قطن 100% بألوان محايدة.', 129, '/demo/kids-4.jpg', 'للطقم', ARRAY['مواليد']::text[], 40),
((SELECT id FROM stores WHERE slug='rijal-thobes'), 'rijal-thobes-1', 'تفصيل ثوب رجالي فاخر', 'قصّة سعودية أو كويتية.', 340, '/demo/fabric-5.jpg', 'للثوب', ARRAY['تفصيل ثياب','خياطة رجالية']::text[], 10),
((SELECT id FROM stores WHERE slug='rijal-thobes'), 'rijal-thobes-2', 'تفصيل مستعجل خلال يوم', 'تسليم خلال 24 ساعة.', 480, '/demo/fabric-6.jpg', 'للثوب', ARRAY['تسليم سريع','تفصيل ثياب']::text[], 20),
((SELECT id FROM stores WHERE slug='rijal-thobes'), 'rijal-thobes-3', 'تعديل ثوب', 'تقصير أو تضييق.', 60, '/demo/fabric-2.jpg', 'للثوب', ARRAY['تعديل']::text[], 30)
ON CONFLICT (slug) DO NOTHING;
COMMIT;
